# Generated by Django 3.1.8 on 2021-10-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
